# Generated by Django 5.0 on 2024-09-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="username",
            field=models.CharField(max_length=50),
        ),
    ]
