# Generated by Django 5.0 on 2024-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0002_alter_customusermodel_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
