# Generated by Django 5.0 on 2024-10-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dialogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dialog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
