# Generated by Django 5.0 on 2024-09-22 13:26

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customusermodel_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customusermodel",
            old_name="home_page",
            new_name="github_page",
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="about_me",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="birth_date",
            field=models.CharField(
                blank=True,
                help_text="Enter birthdate 'DD.MM.YYYY'",
                max_length=10,
                null=True,
                validators=[users.validators.birth_date_validator],
            ),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="job_skills",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="linkedin_page",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="looking_from_job",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[users.validators.phone_number_validator],
            ),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/profile_picture_default.jpg",
                upload_to="static/images/",
                validators=[
                    users.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="website_page",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
