# Generated by Django 5.0 on 2024-09-22 19:23

import django.core.validators
import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_home_page_customusermodel_github_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="followed",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/profile_picture_default.jpg",
                upload_to=users.models.user_directory_path,
                validators=[
                    users.validators.validate_file_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
    ]
