# Generated by Django 5.0 on 2024-09-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_userprofilemodel_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofilemodel",
            name="is_friend",
        ),
    ]
